services:
  - type: web
    name: cyber-threat-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OTX_API_KEY
        sync: false